name: Feeds Package Test Build

on:
  pull_request:

jobs:
  build:
    name: Feeds Package Test Build
    uses: habbie/actions-shared-workflows/.github/workflows/multi-arch-test-build.yml@apk-artifacts
