name: Feeds Package Test Build

on:
  pull_request:

jobs:
  build:
    steps:
      - name: Feeds Package Test Build
        uses: openwrt/actions-shared-workflows/.github/workflows/multi-arch-test-build.yml@main
